services:
  backend-flask:
    env_file:
      - ./backend-flask/.env
    build: ./backend-flask
    ports:
      - "5000:5000"
    volumes:
      - ./backend-flask:/backend-flask
  frontend-react-js:
    env_file:
      - ./frontend-react-js/.env
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
