name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout
      security-events: write # for uploading SARIF results
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # SAST - Snyk Code (Optional: || true prevents pipeline failure)
      - name: Snyk Code test
        run: snyk code test --sarif > snyk-code.sarif || true

      # SCA - Snyk Open Source monitor for backend + frontend
      - name: Python Snyk monitor (backend-flask)
        working-directory: backend-flask
        run: |
          pip install -r requirements.txt
          snyk monitor || true

      - name: Node Snyk monitor (frontend-react-js)
        working-directory: frontend-react-js
        run: |
          npm install
          snyk monitor || true

      # Build and Scan Backend Docker image
      - name: Build backend Docker image
        run: docker build -t backend-image backend-flask/

      - name: Snyk Container monitor (backend)
        run: snyk container monitor backend-image --file=backend-flask/Dockerfile || true

      - name: Snyk Container test (backend)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk container test backend-image --file=backend-flask/Dockerfile

      - name: Snyk Container SARIF output (backend)
        run: snyk container test backend-image --file=backend-flask/Dockerfile --sarif-file-output=container-backend.sarif || true

      - name: Upload Snyk Container SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: container-backend.sarif

      # Build and Scan Frontend Docker image
      - name: Build frontend Docker image
        run: docker build -t frontend-image frontend-react-js/

      - name: Snyk Container monitor (frontend)
        run: snyk container monitor frontend-image --file=frontend-react-js/Dockerfile || true

      - name: Snyk Container test (frontend)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}      
        run: snyk container test frontend-image --file=frontend-react-js/Dockerfile

      - name: Snyk Container SARIF output (frontend)
        run: snyk container test frontend-image --file=frontend-react-js/Dockerfile --sarif-file-output=container-frontend.sarif || true

      - name: Upload Snyk Container SARIF to GitHub Code Scanning (frontend)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: container-frontend.sarif
