name: Snyk Docker Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  snyk-docker-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@v1

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Test backend-flask Dockerfile
        run: snyk container test backend-flask/Dockerfile --file=backend-flask/Dockerfile

      - name: Test frontend-react-js Dockerfile
        run: snyk container test frontend-react-js/Dockerfile --file=frontend-react-js/Dockerfile

      - name: Test postgres Docker image
        run: snyk container test postgres:13-alpine --file=postgres/Dockerfile
